## Copyright 2016, 2025 Elizabeth Rigby
##
## This program is free software: you can redistribute it and/or modify it 
## under the terms of the GNU General Public License as published by the Free 
## Software Foundation, either version 3 of the License, or (at your option) 
## any later version.
##
## This program is distributed in the hope that it will be useful, but WITHOUT 
## ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
## FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for 
## more details.
##
## A copy of the GNU General Public License is stored in the COPYING.txt file 
## along with this program. See also <https://www.gnu.org/licenses/>.
##
###############################################################################

## Summarize / reshape the simulation results for analysis

## load necessary packages
library(reshape)

##NOTE: Lists from Simulation stored but remain in memory for use in this script.
##thus, there is no "load" currently in this script.

##Melt the lists generated by the simulation 
##NOTE: KK and OO not used because computation is too slow
##      r-level summaries through simulation should replace them


YY<-melt.list(ListYOutcomes.y)
#head(YY)

II<-melt.list(ListIOutcomes.yi)
#head(II)

RR<-melt.list(ListROutcomes.yijr)
#head(RR)

#head(ListIRSummaryOutcomes.yi)
IIRR<-melt.list(ListIRSummaryOutcomes.yi)
#head(IIRR)

# KK<-melt.list(ListKOutcomes.yijrk)
# # head(KK)

# #ListOOutcomes.yijrko[[1]][[1]][[1]][[1]][[1]]
# OO<-melt.list(ListOOutcomes.yijrko)
# #head(OO)
# # nrow(OO)
# # nrow(II)
# ## With y=1, i=20, j~40 this takes 10 min.
# ## Object OO has 2 million lines with only y=1,i=20,j~150,r=1,k=60,o=2
# 

############################################
##Cast the data to get useful summaries
## .yi level
{
# cast(II, .~L3, length) ## number of data points for each variable,  (=y*i)
# 
# cast(II, .~L3, mean) ##Mean variable values across all years
# tapply(II$value, II$L3, mean) ##Same results as above, different structure
# 
# cast(II, .~L3+L1, mean) ##Mean variable values, year-specific
# cast(II, .~L3+L2, mean) ##Mean variable values, site-specific

}

# CastTIMER<-proc.time()

#############################################
##Create .y data frame with all necessary columns
YY.data<-cast(YY, ...~L2)
# head(YY.data)

# unique(YY.data$L1)
names(YY.data)[names(YY.data)=="L1"]<-"y"  ##rename columns

if(length(unique(YY.data$y))!=NYears) stop("Verify number of iterations matches parameters")

#############################################
##Create .yi data frame with all necessary columns
II.data<-cast(II, ...~L3)
# head(II.data)
# hist(II.data$NBirds.yi)

# unique(II.data$L1)
names(II.data)[names(II.data)=="L1"]<-"y"  ##rename columns
names(II.data)[names(II.data)=="L2"]<-"i"

if(length(unique(II.data$i))!=NSurveySites) stop("Verify number of sites matches parameters")

########################################
head(IIRR)
IIRR.data<-cast(IIRR, ...~L4)

head(IIRR.data)

#unique(IIRR.data$L1)
names(IIRR.data)[names(IIRR.data)=="L1"]<-"y"  ##rename columns
#unique(IIRR.data$L2)
names(IIRR.data)[names(IIRR.data)=="L2"]<-"i"
#unique(IIRR.data$L3)
names(IIRR.data)[names(IIRR.data)=="L3"]<-"r"


if(length(unique(IIRR.data$r))!=NReps) stop("Verify number of replicationss matches parameters")

########################################

##Create .yijr data frame with all necessary columns
head(RR)
RR.data<-cast(RR, ...~L5)
head(RR.data)
#RR.data

#unique(RR.data$L1)
names(RR.data)[names(RR.data)=="L1"]<-"y"  ##rename columns
#unique(RR.data$L2)
names(RR.data)[names(RR.data)=="L2"]<-"i"
#unique(RR.data$L3)
names(RR.data)[names(RR.data)=="L3"]<-"j"
#unique(RR.data$L4)
names(RR.data)[names(RR.data)=="L4"]<-"r"


##RR.1 replaced by IIRR.data
##For nmixtures, need RR.1
# RR.1<-cast(RR, L1+L2~L5+L4, sum)
# # unique(RR.1$L2)
# # unique(RR.1$L1)
# names(RR.1)[names(RR.1)=="L1"]<-"y"  ##rename columns
# names(RR.1)[names(RR.1)=="L2"]<-"i"
# 
# 
# head(RR.1)


########################################
# ##Create .yijrk data frame with all necessary columns
# # head(KK)
# #nrow(KK)
# #unique(KK$L6)
# 
# # unique(KK$L1) #y
# # unique(KK$L5) #k
# 
# KK.data<-cast(KK, ...~L6)
# # head(KK.data)
# 
# #unique(KK.data$L1)
# #unique(KK.data$L2)
# #unique(KK.data$L3)
# #unique(KK.data$L4)
# #unique(KK.data$L5)
# names(KK.data)[names(KK.data)=="L1"]<-"y"  ##rename columns
# names(KK.data)[names(KK.data)=="L2"]<-"i"
# names(KK.data)[names(KK.data)=="L3"]<-"j"
# names(KK.data)[names(KK.data)=="L4"]<-"r"
# names(KK.data)[names(KK.data)=="L5"]<-"k"
# # 
# length(unique(KK.data$y))==NYears
# length(unique(KK.data$i))==NSurveySites
# length(unique(KK.data$r))==NReps
# length(unique(KK.data$k))==NIntervals
# ##Make sure these are TRUE
# 
# # head(KK.data)
# # 
# # KK.data[KK.data[,"y"]==y & 
# #           KK.data[,"i"]==i & 
# #           KK.data[,"j"]==j &
# #           KK.data[,"r"]==r &
# #           KK.data[,"k"]==k,]

# ###############################################################

##Create .yijrko data frame with all necessary columns
# head(OO)
# nrow(OO)
# unique(OO$L6)
# 
# unique(OO$L1) #y
# unique(OO$L5) #k
# unique(OO$L6) #o
# 
# OO.data<-cast(OO, ...~L7)
# # head(OO.data)
# # nrow(OO.data)
# unique(OO.data$L1)
# unique(OO.data$L2)
# unique(OO.data$L3)
# unique(OO.data$L4)
# unique(OO.data$L5)
# names(OO.data)[names(OO.data)=="L1"]<-"y"  ##rename columns
# names(OO.data)[names(OO.data)=="L2"]<-"i"
# names(OO.data)[names(OO.data)=="L3"]<-"j"
# names(OO.data)[names(OO.data)=="L4"]<-"r"
# names(OO.data)[names(OO.data)=="L5"]<-"k"
# names(OO.data)[names(OO.data)=="L6"]<-"o"
# 
# length(unique(OO.data$y))==NYears
# length(unique(OO.data$i))==NSurveySites
# length(unique(OO.data$r))==NReps
# length(unique(OO.data$k))==NIntervals
# length(unique(OO.data$o))==NSimultaneousObservers
# ##Make sure these are TRUE
# 
# # head(OO.data)
# 

# proc.time()- CastTIMER
# print(paste(SurveyType, "Iteration=",Iteration, "Reshape Complete"))

# OO.data[OO.data[,"y"]==y & 
#           OO.data[,"i"]==i & 
#           OO.data[,"j"]==j &
#           OO.data[,"r"]==r &
#           OO.data[,"k"]==k,]


###########################################################
##Save dataset for future use
DATE<-format(Sys.time(), "%m_%d_%Y")
 AnalysisName<-paste("Analysis",SIMNUM,SurveyType,"Iteration", Iteration, sep="_")

setwd(SaveDirectory)

save(NYears, NSurveySites, NReps, SurveyType, SurveyOptions, 
     NIntervals, NSimultaneousObservers, NTotalObservers, ObserverIDs,
     PrimaryObsNumber.yir.List,
     #PrimaryObsNumber.yir,
     YY.data, IIRR.data, II.data, RR.data, 
     # RR.1,  KK.data, OO.data, 
     file=paste("BTBW_",DATE,"_",AnalysisName,".RData", sep=""))

setwd(MasterDirectory)

#### END SIMULATION SUMMARY ####################################################