# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.dynamics <- function(samples, y, x, p, h, verbose, check_nth, scale_by_mean) {
    .Call(`_bapvar_dynamics`, samples, y, x, p, h, verbose, check_nth, scale_by_mean)
}

.unit_dynamics <- function(samples, y, x, p, h, verbose, check_nth, scale_by_mean) {
    .Call(`_bapvar_unit_dynamics`, samples, y, x, p, h, verbose, check_nth, scale_by_mean)
}

